name: message_parser
description: A flutter library used to parse message request and response for both NIBBS server and Kimono Server
version: 1.0.0
homepage: https://github.com/Octacore19/message_parser.git

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  analyzer_plugin: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.octacoresoftwares.message_parser
        pluginClass: MessageParserPlugin
      ios:
        pluginClass: MessageParserPlugin